### ISSUE TITLE
임의의 컴포넌트를 템플릿에서 생성한 후 그것을 티스토리 글 내에서 사용할 수 있습니까?

### ISSUE THREAD

**Issue by baramofme** [pronist/tidory#1]
saber 나 vuepress 와 같이 vue 문법과 컴포넌트를 게시글 본문에서 쓰고 싶습니다.

예시
https://saber.land/docs/using-vue-in-markdown.html#ltscriptgt-block

https://tidory.com/ 문서를 보았을 때는, 전역 등록한 컴포넌트를 템플릿에서 사용하는 이야기만 나와있네요.

티스토리 글을 쓸 때 

```md
이런 수치가 있습니다.

<CustomChartComponent :someProp="variableX" reference="ㅈㅈ 와 22 에 관한 연구 중">

<script>
export default {
...
data(){
   return {
       variableX: [ 자료1, 자료2, 자료3 ...... ]
   {
}
...

}
</script>
```

이런 식으로 스킨 내부에서 미리 만들고 등록한 컴포넌트를,
- 티스토리 글 작성 시 사용하고
- 사용 시 vue 의 변수를 v-bind 디렉티브로 바인딩 할 수 있는지요.

**Comment by pronist** [comment]
일단 **티도리 프레임워크**에서 전역적으로 등록된 뷰 컴포넌트를 사용해야 할 때, 주의할 점은 사실상 **티스토리 전용 태그를 컴포넌트 내에서 사용하지 않는 점** 이외에는 거의 없습니다. 이 점만 주의한다면 일반적으로 뷰 컴포넌트를 사용하듯 할 수 있습니다. 

티스토리에서 글을 쓸 때 미리 정의된 컴포넌트를 변수와 함께 호출하고 글을 쓰는 경우, 글 로드시 컴포넌트가 ```app.js```에 의해 렌더링되어 컴포넌트가 정상적으로 동작 할 것입니다. 컴포넌트의 렌더링이 시작되기 전에 **티스토리의 전용 태그 치환**이 먼저 진행되기 때문입니다.

여담으로 글을 쓸 때 HTML 모드를 통해 컴포넌트를 직접 사용하는 것은 저도 직접적으로 실험 해 본 것은 아니기 때문에 만약에 뜻대로 동작하지 않는다면 이어서 달아주세요! :)
