### ISSUE TITLE
빌드(production) 문제 문의

### ISSUE THREAD

**Issue by haguri-peng** [pronist/tidory#13]
안녕하세요. 먼저 Tidory 잘 사용하고 있습니다. 🙏

[개발환경]
- Tidory 8.0.5 Version
- Tistory Open API를 활용하여 Vuejs(vue3)로 개발

다름이 아니라 제가 빌드(npm run production)하면서 문제가 발생하여 문의 드리고자 글을 남깁니다.
빌드, 배포 후에 블로그에 접속할 때 app.xxxx.js 파일에서 연결된 다른 script(123.xxxx.js) 파일을 찾지 못하는 문제(ChunkLoadError)가 발생하였습니다.
딱 봐도 path 문제 같아 'tidory.config.js' 내에 'public_path' 를 지정해 보고 다시 빌드를 해봤지만 해결되지 않았습니다.
그래서 해당 부분을 찾아 직접 수정하고 배포하였더니 정상적으로 블로그가 로딩되었습니다.

![Tidory path problem](https://user-images.githubusercontent.com/20597419/186805357-26ea0c4d-a216-4480-8f0b-4a2b12452a11.png)

수정한 부분은 위 Image(/images/app.xxxx.js)와 같으며, 기존 값은 "./images" 이었습니다.
저한테만 발생한 문제일 지 모르나 혹시 몰라서 글을 남깁니다.

**Comment by pronist** [comment]
@haguri-peng 이 부분 한번 점검해보도록 하겠습니다. 감사합니다 :)

**Comment by pronist** [comment]
@haguri-peng Tidory 8.2.1 버전에서 이 문제가 해결된 것으로 파악되었습니다. 제대로 테스트해본 것은 아닌지라 @haguri-peng 님이 작성하신 티스토리 블로그를 빌드해서 다시 되는지 점검도 해보긴 했는데, 또 문제가 생기면 이슈를 다시 열어주시거나 코멘트 남겨주세요.

**Comment by haguri-peng** [comment]
알겠습니다. 버전업 한 다음에 문제가 있으면 다시 말씀드리겠습니다. 감사합니다.
