### ISSUE TITLE
tidory.com 사이드바 안보임

### ISSUE THREAD

**Issue by sh-cho** [pronist/tidory#14]
안녕하세요~

제가 모니터 한대를 세로로 쓰고 있어서 1080x1920 인데요, 이 해상도에서 tidory.com 을 띄우면 사이드바가 안나오고 햄버거버튼 같은것도 없어서 사용이 조금 불편하네요 ㅠㅠ

![image](https://user-images.githubusercontent.com/11611397/188061115-4d491d69-6b4e-49b0-b159-79b54f9aa40f.png)
gitbook처럼 이런 사이드바 토글버튼을 추가하거나 아님 다른 방식으로 사이드바 보여주실 수 있을까요?

아 그리고 이런 프레임워크가 있는지 몰랐네요~ 생각만 하고 있었는데 만드신 분이 있었군요 ..👍  티스토리 파트에 공유 해볼게요~ 만들어주셔서 감사합니다

**Comment by pronist** [comment]
@sh-cho 음 그렇네요. 가로가 좁은 환경에서는 메뉴가 사라져버리니 UX 상 문제가 있군요. 알겠습니다~

**Comment by pronist** [comment]
@sh-cho 사이드바 추가가 완료 되었습니다~
