### ISSUE TITLE
ERROR in [eslint] No ESLint configuration found in \assets.

### ISSUE THREAD

**Issue by Dunzae** [pronist/tidory#16]
![image](https://github.com/user-attachments/assets/60ee0248-a6e9-43d2-a8ce-27991cd53437)

<p>npm run start, npm run preview를 실행했을 때 위와 같은 문제가 발생하며, .eslintrc.js로 변경 시 eslint파일을 읽어들이는 것을 확인했습니다. </p>
<p> 하지만 eslint.config.js로 사용하길 원했고, eslint-webpack-plugin의 현재 2024.12.11일 기준으로 최신 버전인 4.2.0에서
예전 eslint를 사용하는 것을 발견했습니다.  </p>
<p>
8 버전은 eslint.config.js파일을 설정 파일로 기본적으로 인식하지 않고, eslintrc 파일을 기본적으로 인식하여
현재 tidory 프레임워크를 다운로드하여 실행했을 때, 이런 에러가 발생하는 것 같습니다.  
</p>

<p>해결 방법은 아래와 같습니다.</p>
<p>tidory.config.example.js를 아래처럼 수정하면 됩니다.</p>
 <code><pre>
extends (webpackConfig) {
    webpackConfig.plugins = [
      new ESLintPlugin({
        configType : "flat"
      }),
      ...webpackConfig.plugins
    ]
  }
</pre></code>

혹시 저와 같이 에러 만나시는 분 있을까봐 이슈로 남겨놓습니다!

**Comment by pronist** [comment]
@Dunzae 안녕하세요.

제보해주셔서 감사합니다. 저번에 코어소스를 갱신하면서 eslint 도 업그레이드했는데 정작 tidory.config.example.js 는 바꾸지 않았었네요 ㅋㅋ; 수정하여 반영하였습니다. 기여해주셔서 감사합니다.
